#!/bin/bash -e
#
# Copyright 2017 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -euo pipefail

CLUSTER_NAME=${CLUSTER_NAME:-logging-es}
log_dir=/elasticsearch/persistent/${CLUSTER_NAME}/logs
file=${1:-$CLUSTER_NAME.log}
cmd=cat

helpMsg() {
cat <<MSG

 Usage: $0 [options] [file_name]
 Retrieve Elasticsearch log from the log directory.

   options:
     -f                   follow the file in the Elasticsearch log directory.
                          Default: ${log_dir}/${file}
     --help               This message.

MSG
}


while (($#))
do
case $1 in
    -f)
      cmd="tail"
      tail_args="-n 500 -f"
      shift
      file=${1:-$CLUSTER_NAME.log}
      break
      ;;
    --help|-h)
      helpMsg
      exit 0
      ;;
    *)
      ;;
  esac
  shift
done

exec ${cmd} ${tail_args:-} ${log_dir}/${file}
