#!/bin/bash -e
#
# Copyright 2017 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -euo pipefail
source es_util_env

default_params="h=index,shard,prirep,state,unassigned.reason"

helpMsg() {
cat <<MSG

 Usage: $0
 Command to list information about shards

   options:
     --params    The parameters to add to the query string. Default: '${default_params}'

MSG
}

while (($#))
do
case $1 in
    --params=*)
      params=${1#*=}
      ;;
    --help|-h)
      helpMsg
      exit 0
      ;;
  esac
  shift
done

params=${params:-$default_params}

es_util --query=_cat/shards?${params}
