source "https://rubygems.org"
gem 'fluentd', ENV['FLUENTD_VERSION'], :source=>"https://rubygems.org"
gem 'elasticsearch-transport'
gem 'elasticsearch-api'
gem 'elasticsearch'
gem 'fluent-plugin-kubernetes_metadata_filter'
gem 'fluent-plugin-cloudwatch-logs'
gem 'fluent-plugin-concat'
gem 'fluent-plugin-elasticsearch'
gem 'fluent-plugin-kafka'
gem 'fluent-plugin-grafana-loki'
gem 'fluent-plugin-multi-format-parser'
gem 'fluent-plugin-record-modifier'
gem 'fluent-plugin-rewrite-tag-filter'
gem 'fluent-plugin-systemd'
gem 'fluent-plugin-remote-syslog'
gem 'fluent-plugin-prometheus'
gem 'fluent-plugin-splunk-hec'
gem 'fluent-plugin-label-router'
gem 'typhoeus'
gem 'oj'
gem 'bigdecimal'

#Below gem(and two of its dependencies) are moved to O_A_L/fluentd/lib, but its dependencies still exist in O_A_L/fluentd/vendored_gem_src/
#gem 'fluent-plugin-remote_syslog', '1.0.0'

gem 'ffi', '1.11.3'
gem 'uuidtools', '2.1.5'
gem 'rake'
