---
apiVersion: v1
kind: Template
metadata:
  name: elastalert-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: elastalert
    name: elastalert
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: elastalert
    name: elastalert
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'elastalert:latest'
    source:
      git:
        uri: ${LOGGING_FORK_URL}
        ref: ${LOGGING_FORK_BRANCH}
      contextDir: elastalert
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile.centos7
      type: Docker
    resources:
      limits:
        cpu: 1500m
        memory: 3584Mi
parameters:
-
  description: 'URL for origin-aggregated-logging fork'
  name: LOGGING_FORK_URL
  value: https://github.com/openshift/origin-aggregated-logging
-
  description: 'branch for origin-aggregated-logging fork'
  name: LOGGING_FORK_BRANCH
  value: master
