# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'cucumber', '2.0.0'
gem 'json_pure'
gem 'watir', '6.8.4'
gem 'headless'
