apiVersion: "v1"
kind: "Template"
metadata:
  name: logging-support-template-maker
  annotations:
    description: "Template to create template for deploying logging support entities"
    tags: "infrastructure"
parameters:
-
  description: "A shared secret for the authentication proxy oauth client in front of Kibana"
  name: OAUTH_SECRET
  required: true
-
  description: "Hostname at which users will visit Kibana and be authenticated."
  name: KIBANA_HOSTNAME
  required: true
-
  description: "Hostname at which admins will visit the ops Kibana."
  name: KIBANA_OPS_HOSTNAME
  value: kibana-ops.example.com
-
  description: 'Specify prefix for logging component images; e.g. for "openshift/origin-logging-deployment:v1.1", set prefix "openshift/origin-"'
  name: IMAGE_PREFIX_DEFAULT
  value: "docker.io/openshift/origin-"
-
  description: 'Set to "true" if the image registry is not secured with a properly-signed certificate.'
  name: INSECURE_REGISTRY
  value: "false"
objects:
- apiVersion: "v1"
  kind: "Template"
  metadata:
    name: logging-support-template
    annotations:
      description: "Template for deploying logging services, service accounts, and oauthclient."
      tags: "infrastructure"
    labels:
      logging-infra: support
  labels:
    logging-infra: support
    provider: openshift
    component: support
  objects:
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-es"
    spec:
      ports:
      -
        port: 9200
        targetPort: restapi
      selector:
        provider: "openshift"
        component: "es"
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-es-cluster"
    spec:
      portalIP: "None"
      ports:
      -
        port: 9300
      selector:
        provider: "openshift"
        component: "es"
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-es-ops"
    spec:
      ports:
      -
        port: 9200
        targetPort: restapi
      selector:
        provider: "openshift"
        component: "es-ops"
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-es-ops-cluster"
    spec:
      portalIP: "None"
      ports:
      -
        port: 9300
      selector:
        provider: "openshift"
        component: "es-ops"
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-kibana"
    spec:
      ports:
        -
          port: 443
          targetPort: "oaproxy"
      selector:
        provider: openshift
        component: "kibana"
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-kibana-ops"
    spec:
      ports:
        -
          port: 443
          targetPort: "oaproxy"
      selector:
        provider: openshift
        component: "kibana-ops"
  -
    apiVersion: v1
    kind: OAuthClient
    metadata:
      name: kibana-proxy
    secret: ${OAUTH_SECRET}
    redirectURIs:
    - https://${KIBANA_HOSTNAME}
    - https://${KIBANA_OPS_HOSTNAME}
- apiVersion: "v1"
  kind: "Template"
  metadata:
    name: logging-imagestream-template
    annotations:
      description: "Template for deploying logging support entities: imagestreams."
      tags: "infrastructure"
    labels:
      logging-infra: support
  labels:
    logging-infra: support
    provider: openshift
    component: support
  parameters:
  -
    description: 'Specify prefix for logging component images; e.g. for "openshift/origin-logging-deployer:v1.1", set prefix "openshift/origin-"'
    name: IMAGE_PREFIX
    value: ${IMAGE_PREFIX_DEFAULT}
  objects:
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "${INSECURE_REGISTRY}"
      name: logging-auth-proxy
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-auth-proxy
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "${INSECURE_REGISTRY}"
      name: logging-elasticsearch
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-elasticsearch
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "${INSECURE_REGISTRY}"
      name: logging-fluentd
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-fluentd
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "${INSECURE_REGISTRY}"
      name: logging-kibana
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-kibana
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "${INSECURE_REGISTRY}"
      name: logging-curator
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-curator
- apiVersion: "v1"
  kind: "Template"
  parameters:
  -
    description: "The name for the PVC"
    name: NAME
    required: true
  -
    description: "The size for the PVC"
    name: SIZE
    required: true
  metadata:
    name: logging-pvc-template
    annotations:
      description: "Template for deploying logging support entities: persistentvolumeclaims."
      tags: "infrastructure"
    labels:
      logging-infra: support
  labels:
    logging-infra: support
    provider: openshift
    component: support
  objects:
  -
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${NAME}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: ${SIZE}
