apiVersion: "v1"
kind: "Template"
metadata:
  name: logging-support-template-maker
  annotations:
    description: "Template to create template for deploying logging support entities"
    tags: "infrastructure"
parameters:
-
  description: "A shared secret for the authentication proxy oauth client in front of Kibana"
  name: OAUTH_SECRET
  required: true
-
  description: "Hostname at which users will visit Kibana and be authenticated."
  name: KIBANA_HOSTNAME
  required: true
-
  description: "Hostname at which admins will visit the ops Kibana."
  name: KIBANA_OPS_HOSTNAME
  value: kibana-ops.example.com
-
  description: 'Specify prefix for logging component images; e.g. for "openshift/origin-logging-deployment:v1.1", set prefix "openshift/origin-"'
  name: IMAGE_PREFIX_DEFAULT
  value: "docker.io/openshift/origin-"
objects:
- apiVersion: "v1"
  kind: "Template"
  metadata:
    name: logging-support-template
    annotations:
      description: "Template for deploying logging services, service accounts, and oauthclient."
      tags: "infrastructure"
    labels:
      logging-infra: support
  labels:
    logging-infra: support
    provider: openshift
    component: support
  objects:
  -
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: aggregated-logging-kibana
    secrets:
      - name: logging-kibana
      - name: logging-kibana-proxy
      - name: logging-kibana-ops-proxy
  -
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: aggregated-logging-elasticsearch
    secrets:
      - name: logging-elasticsearch
  -
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: aggregated-logging-fluentd
    secrets:
      - name: logging-fluentd
  -
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: aggregated-logging-curator
    secrets:
      - name: logging-curator
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-es"
    spec:
      ports:
      -
        port: 9200
        targetPort: restapi
      selector:
        provider: "openshift"
        component: "es"
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-es-cluster"
    spec:
      portalIP: "None"
      ports:
      -
        port: 9300
      selector:
        provider: "openshift"
        component: "es"
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-es-ops"
    spec:
      ports:
      -
        port: 9200
        targetPort: restapi
      selector:
        provider: "openshift"
        component: "es-ops"
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-es-ops-cluster"
    spec:
      portalIP: "None"
      ports:
      -
        port: 9300
      selector:
        provider: "openshift"
        component: "es-ops"
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-kibana"
    spec:
      ports:
        -
          port: 443
          targetPort: "oaproxy"
      selector:
        provider: openshift
        component: "kibana"
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-kibana-ops"
    spec:
      ports:
        -
          port: 443
          targetPort: "oaproxy"
      selector:
        provider: openshift
        component: "kibana-ops"
  -
    apiVersion: v1
    kind: OAuthClient
    metadata:
      name: kibana-proxy
    secret: ${OAUTH_SECRET}
    redirectURIs:
    - https://${KIBANA_HOSTNAME}
    - https://${KIBANA_OPS_HOSTNAME}
- apiVersion: "v1"
  kind: "Template"
  metadata:
    name: logging-imagestream-template
    annotations:
      description: "Template for deploying logging support entities: imagestreams."
      tags: "infrastructure"
    labels:
      logging-infra: support
  labels:
    logging-infra: support
    provider: openshift
    component: support
  parameters:
  -
    description: 'Specify prefix for logging component images; e.g. for "openshift/origin-logging-deployer:v1.1", set prefix "openshift/origin-"'
    name: IMAGE_PREFIX
    value: ${IMAGE_PREFIX_DEFAULT}
  objects:
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "true"
      name: logging-auth-proxy
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-auth-proxy
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "true"
      name: logging-elasticsearch
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-elasticsearch
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "true"
      name: logging-fluentd
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-fluentd
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "true"
      name: logging-kibana
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-kibana
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "true"
      name: logging-curator
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-curator

