source 'https://rubygems.org'

gem 'remote_syslog_sender', path: "../remote_syslog_sender/"
gem "syslog_protocol", path: "../syslog_protocol/"

# Specify your gem's dependencies in fluent-plugin-remote_syslog.gemspec
gemspec
