apiVersion: "v1"
kind: "Template"
metadata:
  name: logging-curator-template-maker
  annotations:
    description: "Template to create template for deploying curator"
    tags: "infrastructure"
objects:
- apiVersion: "v1"
  kind: "Template"
  metadata:
    name: logging-${CURATOR_DEPLOY_NAME}-template
    annotations:
      description: "Template for logging curator deployment."
      tags: "infrastructure"
    labels:
      logging-infra: curator
  labels:
    logging-infra: curator
    provider: openshift
    component: ${CURATOR_DEPLOY_NAME}
  parameters:
  -
    description: "The version tag of the image to use."
    name: IMAGE_VERSION
    value: ${IMAGE_VERSION_DEFAULT}
  -
    name: IMAGE_PREFIX
    value: ${IMAGE_PREFIX_DEFAULT}
  objects:
  -
    apiVersion: v1
    kind: "DeploymentConfig"
    metadata:
      name: "logging-${CURATOR_DEPLOY_NAME}"
      labels:
        provider: openshift
        component: "${CURATOR_DEPLOY_NAME}"
    spec:
      replicas: 1
      selector:
        provider: openshift
        component: "${CURATOR_DEPLOY_NAME}"
      triggers: {}
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Recreate
      template:
        metadata:
          name: ${CURATOR_DEPLOY_NAME}
          labels:
            provider: openshift
            component: "${CURATOR_DEPLOY_NAME}"
        spec:
          serviceAccountName: aggregated-logging-curator
          containers:
          - name: curator
            image: ${IMAGE_PREFIX}logging-curator:${IMAGE_VERSION}
            resources:
              limits:
                cpu: 100m
            volumeMounts:
            - name: certs
              mountPath: /etc/curator/keys
              readOnly: true
            - name: config
              mountPath: /etc/curator/settings
              readOnly: true
            env:
            - name: "K8S_HOST_URL"
              value: ${MASTER_URL}
            - name: "ES_HOST"
              value: ${ES_HOST}
            - name: "ES_PORT"
              value: ${ES_PORT}
            - name: "ES_CLIENT_CERT"
              value: ${ES_CLIENT_CERT}
            - name: "ES_CLIENT_KEY"
              value: ${ES_CLIENT_KEY}
            - name: "ES_CA"
              value: ${ES_CA}
            - name: "CURATOR_DEFAULT_DAYS"
              value: ${CURATOR_DEFAULT_DAYS}
            - name: "CURATOR_RUN_HOUR"
              value: ${CURATOR_RUN_HOUR}
            - name: "CURATOR_RUN_MINUTE"
              value: ${CURATOR_RUN_MINUTE}
            - name: "CURATOR_RUN_TIMEZONE"
              value: ${CURATOR_RUN_TIMEZONE}
            - name: "CURATOR_SCRIPT_LOG_LEVEL"
              value: ${CURATOR_SCRIPT_LOG_LEVEL}
            - name: "CURATOR_LOG_LEVEL"
              value: ${CURATOR_LOG_LEVEL}
          volumes:
          - name: certs
            secret:
              secretName: logging-${CURATOR_DEPLOY_NAME}
          - name: config
            configMap:
              name: logging-curator
parameters:
-
  name: CURATOR_DEPLOY_NAME
  description: "Modify to differentiate regular and ops Curator."
  value: "curator"
-
  description: "Internal url for reaching the master API to query pod labels"
  name: MASTER_URL
  value: "https://kubernetes.default.svc.cluster.local"
-
  description: "Hostname (or IP) for reaching Elasticsearch"
  name: ES_HOST
  value: "logging-es"
-
  description: "Port number for reaching Elasticsearch"
  name: ES_PORT
  value: "9200"
-
  description: "Location of client certificate for authenticating to Elasticsearch"
  name: ES_CLIENT_CERT
  value: "/etc/curator/keys/cert"
-
  description: "Location of client key for authenticating to Elasticsearch"
  name: ES_CLIENT_KEY
  value: "/etc/curator/keys/key"
-
  description: "Location of CA cert for validating connecting to Elasticsearch"
  name: ES_CA
  value: "/etc/curator/keys/ca"
-
  description: "(Deprecated) The default number of days that logs will be retained for a project if an index management configuration for it is not provided"
  name: CURATOR_DEFAULT_DAYS
  value: "31"
-
  description: "(Deprecated) The hour of the day (24 hour format) at which to run the curator jobs."
  name: CURATOR_RUN_HOUR
  value: "0"
-
  description: "(Deprecated) The minute of the hour at which to run the curator jobs."
  name: CURATOR_RUN_MINUTE
  value: "0"
-
  description: "(Deprecated) The timezone of the runhour and runminute for the curator jobs."
  name: CURATOR_RUN_TIMEZONE
  value: "UTC"
-
  description: "The version tag of the image to use."
  name: IMAGE_VERSION_DEFAULT
  value: "latest"
- name: IMAGE_PREFIX_DEFAULT
-
  description: "Log level for script that runs curator - one of CRITICAL, ERROR, WARNING, INFO or DEBUG"
  name: CURATOR_SCRIPT_LOG_LEVEL
  value: "INFO"
-
  description: "Log level for curator command - one of CRITICAL, ERROR, WARNING, INFO or DEBUG"
  name: CURATOR_LOG_LEVEL
  value: "ERROR"
