apiVersion: "v1"
kind: "Template"
metadata:
  name: logging-kibana-template-maker
  annotations:
    description: "Template to create template for deploying Kibana"
    tags: "infrastructure"
objects:
- apiVersion: "v1"
  kind: "Template"
  metadata:
    name: logging-${KIBANA_DEPLOY_NAME}-template
    annotations:
      description: "Template for deploying log viewer Kibana connecting to Elasticsearch to visualize aggregated cluster logs."
      tags: "infrastructure"
    labels:
      logging-infra: kibana
  labels:
    logging-infra: kibana
    provider: openshift
    component: ${KIBANA_DEPLOY_NAME}
  parameters:
  -
    description: "The version tag of the image to use."
    name: IMAGE_VERSION
    value: ${IMAGE_VERSION_DEFAULT}
  -
    name: IMAGE_PREFIX
    value: ${IMAGE_PREFIX_DEFAULT}
  objects:
  -
    apiVersion: "v1"
    kind: "DeploymentConfig"
    metadata:
      name: "logging-${KIBANA_DEPLOY_NAME}"
      labels:
        provider: openshift
        component: "${KIBANA_DEPLOY_NAME}"
    spec:
      replicas: 1
      selector:
        provider: openshift
        component: "${KIBANA_DEPLOY_NAME}"
      triggers: {}
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          name: "${KIBANA_DEPLOY_NAME}"
          labels:
            provider: openshift
            component: "${KIBANA_DEPLOY_NAME}"
        spec:
          serviceAccountName: aggregated-logging-kibana
          containers:
            -
              name: "kibana"
              image: ${IMAGE_PREFIX}logging-kibana:${IMAGE_VERSION}
              ports:
              env:
                - name: "ES_HOST"
                  value: ${ES_HOST}
                - name: "ES_PORT"
                  value: ${ES_PORT}
              volumeMounts:
                - name: kibana
                  mountPath: /etc/kibana/keys
                  readOnly: true
            -
              name: "kibana-proxy"
              image: ${IMAGE_PREFIX}logging-auth-proxy:${IMAGE_VERSION}
              ports:
                -
                  name: "oaproxy"
                  containerPort: 3000
              env:
                -
                  name: "OAP_BACKEND_URL"
                  value: "http://localhost:5601"
                -
                  name: "OAP_AUTH_MODE"
                  value: "oauth2"
                -
                  name: "OAP_TRANSFORM"
                  value: "user_header,token_header"
                -
                  name: "OAP_OAUTH_ID"
                  value: kibana-proxy
                -
                  name: "OAP_MASTER_URL"
                  value: ${OAP_MASTER_URL}
                -
                  name: "OAP_PUBLIC_MASTER_URL"
                  value: ${OAP_PUBLIC_MASTER_URL}
                -
                  name: "OAP_LOGOUT_REDIRECT"
                  value: ${OAP_PUBLIC_MASTER_URL}/console/logout
                -
                  name: "OAP_MASTER_CA_FILE"
                  value: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
                -
                  name: "OAP_DEBUG"
                  value: ${OAP_DEBUG}
              volumeMounts:
                - name: kibana-proxy
                  mountPath: /secret
                  readOnly: true
          volumes:
            - name: kibana
              secret:
                secretName: logging-kibana
            - name: kibana-proxy
              secret:
                secretName: logging-kibana-proxy
parameters:
-
  name: KIBANA_DEPLOY_NAME
  description: "Modify to differentiate regular and ops UI."
  value: "kibana"
-
  description: "Internal URL for the master, for authentication retrieval"
  name: OAP_MASTER_URL
  value: "https://kubernetes.default.svc.cluster.local"
-
  description: "Public URL for the master, for sending the browser to authenticate"
  name: OAP_PUBLIC_MASTER_URL
  required: true
-
  description: "Hostname/IP for Elasticsearch backend to connect to."
  name: ES_HOST
  value: "logging-es"
-
  description: "Port to connect to for Elasticsearch backend."
  name: ES_PORT
  value: "9200"
-
  description: "Show extra proxy debug information at startup and during operations"
  name: OAP_DEBUG
  value: "false"
-
  description: "The version tag of the image to use."
  name: IMAGE_VERSION_DEFAULT
  value: "latest"
- name: IMAGE_PREFIX_DEFAULT
