#!/bin/bash -e
set -euo pipefail

LOGGING_FILE_PATH=${LOGGING_FILE_PATH:-/var/log/rsyslog/rsyslog.log}
log_dir=`dirname ${LOGGING_FILE_PATH}`
log_file=`basename ${LOGGING_FILE_PATH}`
pod_dir=${RSYSLOG_WORKDIRECTORY:-/var/lib/rsyslog.pod}
cmd=cat

helpMsg() {
cat <<MSG
 Usage: $0 [options]
 Retrieve Rsyslog logs from the log directory using "LOGGING_FILE_PATH" environment variable.
   Options:
     -f                   Follow the log file in the rsyslog log directory.
                          Default log file is "rsyslog.log".
     -a --all             Including logrotation logs.  Ignored if -f is set.
     -h --help            Prints out help.
MSG
}

tail_args=""
include_logrotation="false"
while (($#))
do
case $1 in
    -f)
      cmd="tail"
      tail_args="-f"
      break
      ;;
    --all|-a)
      include_logrotation="true"
      ;;
    --help|-h)
      helpMsg
      exit 0
      ;;
    *)
      ;;
  esac
  shift
done

if [ $cmd = "cat" ] ; then
    if [ "$include_logrotation" = "true" ] ; then
        if ls $log_dir/${log_file}* > /dev/null 2>&1 ; then
            echo "===== rsyslog logs ====="
            for file in $( ls $log_dir/${log_file}* | sort -Vr ); do
                cat $file
            done
        fi
        if ls $log_dir/rsyslog_debug.* > /dev/null 2>&1 ; then
            echo ""
            echo "===== rsyslog debug logs ====="
            for file in $( ls $log_dir/rsyslog_debug.* | sort -Vr ); do
                cat $file
            done
        fi
        if ls $log_dir/logrotate* > /dev/null 2>&1 ; then
            echo ""
            echo "===== logrotation logs ($log_dir) ====="
            for file in $( ls $log_dir/logrotate* | sort -Vr ); do
                cat $file
            done
        fi
        if ls $pod_dir/logrotate* > /dev/null 2>&1 ; then
            echo ""
            echo "===== logrotation logs ($pod_dir) ====="
            for file in $( ls $pod_dir/logrotate* | sort -Vr ); do
                cat $file
            done
        fi
    else
        if ls $log_dir/${log_file}* > /dev/null 2>&1 ; then
            for file in $( ls $log_dir/${log_file}* | sort -Vr ); do
                cat $file
            done
        fi
    fi
else
    exec tail "$tail_args" $log_dir/$log_file
fi
