#!/bin/bash

# prep the environment to allow bailing early on failures
# setup ansible
WORKDIR=$(mktemp -d)
ANSIBLE_RPM=${ANSIBLE_RPM:-ansible-2.2.1.0-1.el7.noarch}
ANSIBLE_INSTALL_CMD=${ANSIBLE_INSTALL_CMD:-"sudo yum install $ANSIBLE_RPM -y"}
RUAMEL_YAML_INSTALL_CMD=${RUAMEL_YAML_INSTALL_CMD:-"sudo yum install python2-ruamel-yaml -y"}

OS_ANSIBLE_REPO=${OS_ANSIBLE_REPO:-https://github.com/openshift/openshift-ansible}
OS_ANSIBLE_BRANCH=${OS_ANSIBLE_BRANCH:-master}
OS_ANSIBLE_DIR=$WORKDIR/openhift-ansible

sudo yum makecache fast
sudo yum install python2-pip -y
$ANSIBLE_INSTALL_CMD
$RUAMEL_YAML_INSTALL_CMD

git clone $OS_ANSIBLE_REPO $OS_ANSIBLE_DIR -b $OS_ANSIBLE_BRANCH --depth=1

# make sure binaries are in the desired place
# hack - ansible should find whichever binaries 
for oc_binary in oc oadm
do
  if [ ! -f /usr/local/bin/$oc_binary ]; then
    echo "Copying $oc_binary from path to /usr/local/bin for use by openshift-ansible"
    sudo cp `which $oc_binary` /usr/local/bin
  else
    echo "Found $oc_binary in /usr/local/bin for use by openshift-ansible"
  fi
  if [ ! -f /usr/bin/$oc_binary ]; then
    echo "Copying $oc_binary from path to /usr/bin for use by openshift-ansible"
    sudo cp `which $oc_binary` /usr/bin
  fi
done

export PATH=/usr/local/bin:$PATH
