#!/bin/bash

# prep the environment to allow bailing early on failures
# setup ansible
WORKDIR=$(mktemp -d)
ANSIBLE_RPM=${ANSIBLE_RPM:-ansible-2.2.0.0-1.el7.noarch}
RUAMEL_YAML_RPM=${ANSIBLE_RPM:-python2-ruamel-yaml-0.12.14-6.el7.x86_64}

OS_ANSIBLE_REPO=${OS_ANSIBLE_REPO:-https://github.com/openshift/openshift-ansible}
OS_ANSIBLE_BRANCH=${OS_ANSIBLE_BRANCH:-master}
OS_ANSIBLE_DIR=$WORKDIR/openhift-ansible

PUDDLE_URL=${PUDDLE_URL:""}

if [ ! -z $PUDDLE_URL ]; then
  sudo wget $PUDDLE_URL/puddle.repo -O /etc/yum.repos.d/puddle.repo
fi

sudo yum makecache fast
sudo yum install python2-pip $RUAMEL_YAML_RPM $ANSIBLE_RPM -y

git clone $OS_ANSIBLE_REPO $OS_ANSIBLE_DIR -b $OS_ANSIBLE_BRANCH --depth=1

# make sure binaries are in the desired place
# hack - ansible should find whichever binaries 
for oc_binary in oc oadm
do
  if [ ! -f /usr/local/bin/$oc_binary ]; then
    echo "Copying $oc_binary from path to /usr/local/bin for use by openshift-ansible"
    sudo cp `which $oc_binary` /usr/local/bin
  else
    echo "Found $oc_binary in /usr/local/bin for use by openshift-ansible"
  fi
  if [ ! -f /usr/bin/$oc_binary ]; then
    echo "Copying $oc_binary from path to /usr/bin for use by openshift-ansible"
    sudo cp `which $oc_binary` /usr/bin
  fi
done

export PATH=/usr/local/bin:$PATH
