#!/bin/bash -e
#
# Copyright 2018 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "logging"

info Adding ingest pipelines
shopt -s failglob
for ingest_file in ${ES_HOME}/ingest_pipelines/*.json
do

    template=`basename $ingest_file`
    # Check if ingest template already exists
    response_code=$(es_util --query=_ingest/pipeline/$template \
        ${DEBUG:+-v} -s \
        --request HEAD --head --output /dev/null \
        -w '%{response_code}')
    if [ "${response_code}" == "200" ]; then
        info "Ingest pipeline '$template' found in the cluster, overriding it"
    else
        info "Create ingest pipeline '$template'"
    fi
    es_util --query=_ingest/pipeline/$template \
        ${DEBUG:+-v} -s -X PUT \
        -d@${ingest_file}

done
shopt -u failglob
info Finished adding ingest pipelines
