apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterloggings.logging.openshift.io
spec:
  group: logging.openshift.io
  names:
    kind: ClusterLogging
    listKind: ClusterLoggingList
    plural: clusterloggings
    singular: clusterlogging
  scope: Namespaced
  version: v1alpha1
