#!/bin/bash -eu
#
# Utility to check the overall state of the cluster via various _cat APIs.
#
source es_util_env

date
NODATE=true health
es_util --query="_cat/nodes?v"
NODATE=true indices | grep -vE "^green"
NODATE=true indices | grep "searchguard"
es_util --query="_cat/count?v"
NODATE=true thread_pool
sleep 5
es_util --query="_cat/count?v"
NODATE=true thread_pool
date
