#!/bin/bash -e
#
# Copyright 2017 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Utility to grab documents from the ES
# instance using the admin certs and keys
set -euo pipefail
source es_util_env

while (($#))
do
case $1 in
    --query=*)
      QUERY=${1#*=}
      ;;
    *)
      echo Ignoring unknown argument $1
      ;;
  esac
  shift
done

QUERY=${QUERY:-""}
INDEX=${INDEX:-"project.*"}
TYPE=${TYPE:-"_search"}
SIZE=${SIZE:-10}
SORT=${SORT:-"@timestamp:desc"}
OPTIONS=${OPTIONS:-"size=$SIZE&sort=$SORT&pretty"}

ES_BASE=${ES_BASE:-https://localhost:9200}

if [ -z "${QUERY:-}" ]; then
  QUERY="$INDEX/$TYPE?$OPTIONS"
fi

curl -s -k --cert /etc/elasticsearch/secret/admin-cert --key /etc/elasticsearch/secret/admin-key "$ES_BASE/$QUERY" "$@"
