apiVersion: v1
kind: "Template"
metadata:
  name: logging-dev-build-template
  annotations:
    description: "Template for creating local builds of logging components from source."
    tags: "infrastructure"
labels:
  logging-infra: development
  provider: openshift
  component: development
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: logging-elasticsearch
    name: centos
  spec:
    dockerImageRepository: library/centos:7
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: logging-deployment
    name: logging-deployment
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: logging-elasticsearch
    name: logging-elasticsearch
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: logging-fluentd
    name: logging-fluentd
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: logging-kibana
    name: logging-kibana
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: logging-auth-proxy
    name: logging-auth-proxy
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: logging-deployment
    name: origin
  spec:
    dockerImageRepository: openshift/origin:latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: logging-deployment
    name: logging-deployment
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: logging-deployment:latest
    resources: {}
    source:
      contextDir: deployment
      git:
        uri: ${LOGGING_FORK_URL}
        ref: ${LOGGING_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: origin:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: logging-elasticsearch
    name: logging-elasticsearch
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: logging-elasticsearch:latest
    resources: {}
    source:
      contextDir: elasticsearch
      git:
        uri: ${LOGGING_FORK_URL}
        ref: ${LOGGING_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:7
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: logging-fluentd
    name: logging-fluentd
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: logging-fluentd:latest
    resources: {}
    source:
      contextDir: fluentd
      git:
        uri: ${LOGGING_FORK_URL}
        ref: ${LOGGING_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:7
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: logging-kibana
    name: logging-kibana
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: logging-kibana:latest
    resources: {}
    source:
      contextDir: kibana
      git:
        uri: ${LOGGING_FORK_URL}
        ref: ${LOGGING_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: openshift/base-centos7
      type: Docker
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: logging-auth-proxy
    name: logging-auth-proxy
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: logging-auth-proxy:latest
    resources: {}
    source:
      git:
        uri: ${PROXY_FORK_URL}
        ref: ${PROXY_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: library/node:0.10.36
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
-
  description: 'URL for origin-aggregated-logging fork'
  name: LOGGING_FORK_URL
  value: https://github.com/openshift/origin-aggregated-logging
-
  description: 'branch for origin-aggregated-logging fork'
  name: LOGGING_FORK_BRANCH
  value: master
-
  description: 'URL for origin-auth-proxy fork'
  name: PROXY_FORK_URL
  value: https://github.com/fabric8io/openshift-auth-proxy
-
  description: 'branch for origin-auth-proxy fork'
  name: PROXY_FORK_BRANCH
  value: master
