FROM registry.svc.ci.openshift.org/ocp/builder:ubi8.ruby.25
MAINTAINER OpenShift Development <dev@lists.openshift.redhat.com>

ENV FLUENTD_VERSION=1.0 \
    WORKDIR=/tmp/fluentd/lib

USER 0
ENTRYPOINT /tmp/run.sh
ENV GEM_HOME=/tmp/vendor
RUN gem install rake bundler --no-ri --no-doc
WORKDIR ${WORKDIR}
COPY test/unit/run.sh /tmp/
COPY fluentd/lib ${WORKDIR}
RUN for d in $(ls $WORKDIR) ; do \
    pushd ${d} ; \
        bundle install ; \
    popd ; \
    done
RUN /tmp/run.sh
